### ISSUE TITLE
I have met the error "module 'models/init' not found"

### ISSUE THREAD

**Issue by bemoregt** [erogol/beauty.torch#1]
Hi, @erogol 

I have met the error "module 'models/init' not found"

My error message here:
---------------------------------------------------------------------------
module 'models/init' not found:No LuaRocks module found for models/initmodule 'models/init' not found:No LuaRocks module found for models/init

OS: Ubuntu14.04
Torch7

**Comment by erogol** [comment]
it is an torch module. You can install by ```luarocks install nninit```

**Comment by bemoregt** [comment]
Oh Thanks ~

나의 iPhone에서 보냄

2017. 4. 29. 오전 7:51 Eren Golge <notifications@github.com> 작성:
